vich_uploader:
    db_driver: orm

    mappings:
        recipes:
            uri_prefix: /asset/images/recipes
            upload_destination: '%kernel.project_dir%/public/asset/images/recipes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
